version: "3"
services:
  typesense:
    container_name: typesense-node
    image:  typesense/typesense:0.25.1
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=showzeraboladera --enable-cors"
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
volumes:
  typesense-data:
    driver: local
